### ISSUE TITLE
alignyfy treats double bonds as equality

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#6] opened 2018-08-17 11:14 UTC
Say you write this hypothetical reaction equation:
```
\ce{H2C=O + H2O <=> H2C(OH)2}
```
You can use alignify to destroy it:
```
$$\begin{align}
\ce{H2C&=O + H2O <&=> H2C(OH)2}
\end{align}$$
```
It should not recognise double bonds as equality signs. And it must treat `<=>` as one unit. The last issue might already be fixed with the recent additions referred in #5, i.e. in [255](https://github.com/GaurangTandon/MarkdownShortcutsForSE/blob/5fe2979e2e45ba2c94c38a650b95180ec2982bb1/MarkdownShortcutsSE.user.js#L255). (You should also bump the version when you commit, so that we can easier track if we have the most recent version running.)

**Comment by GaurangTandon** [comment] 2018-08-18 10:04
Okay, this is interesting. What happens is that: suppose you're on Math.SE, then it may be common for you to type `a=b` and expect the alignment to take place at `a&=b`. This is what I had in mind first. However, the same doesn't apply to Chem.SE (and also Bio.SE) as I now realise. So, I can have separate check for Chem.SE to only apply alignment to equals sign if it is _not_ surrounded on _both_ sides by a character.

> You should also bump the version when you commit, so that we can easier track if we have the most recent version running

Whoops, silly oversight.

**Comment by GaurangTandon** [comment] 2018-09-26 08:21
I am unable to reproduce this issue in the latest v1.7.0 update. Closing for now.

**Closed as completed by GaurangTandon** 2018-09-26 08:21 UTC
Labels: bug
